@Library('grooji')
import com.grooji.*;

def execute() {
  node() {

    stage("Add git tag and push them to server") {
      def pod = getPodsByNamespace('dev');
      def recent = getRecentPodStatus('pod-begins-with...', 'dev');
      def running = getRunningPodStatus('pod-begins-with...', 'dev');
	  def podNameByRegex = getPodNameByRegex('pod-begins-with...', 'dev');
    }
  }
}
