@Library('grooji')
import com.grooji.*;

def execute() {
  node() {

    stage("Do something...") {
      def _step = 'currently doing this';
      def stepReturn = setRecentStep(_step);

      assertEquals(stepReturn, 'currently doing this');
      assertEquals(recentStep, stepReturn);
    }
  }
}
