@Library('grooji')
import com.grooji.*;

def execute() {
  node() {

    stage("Send some slack messages") {
      def slack = com.grooji.SlackNotification;
      pushSlackNotification('color', 'action', 'appName', 'targetEnv', 'build', 'log', 'recentStage');
      pushSlackNotification('color', 'action', 'appName', 'targetEnv', 'build', 'log');
      pushSlackNotification('color', 'action', 'appName', 'targetEnv', 'build');
      pushSlackNotification('color', 'action', 'appName', 'targetEnv');
      pushSlackNotification('color', 'action', 'appName');
      pushSlackNotification(slack.COLOR_INFO, slack.BUILD_START, 'appName');
    }
  }
}
